### PR TITLE
5.24 support

### PR DESCRIPTION
**Pull request by teunvdingenen**
I got most the changes down to generate 5.24 content. If possible it would be nice to get some people to use this code so I can get more feedback on things that are working and are not. There isn't much more I can do at the moment.

There is one remaining problem right now and that is that the cli is generating identical pages for summoned creatures. For example "undead spirit" is getting 7 entires that are the same. I'm not sure if this is a bug or not but either way I can't figure out how to resolve.

Also there seems to have been a change in how features or monsters are being categorized. The effect is that variants aren't correctly being found. I think it's best to wait for future releases of dmg and mm before making big changes. For now it does seem to generate all content you would want.

### CODE REVIEW

**Comment by ebullient** [comment]
Those 7 entries should not be identical. I'll double check. There should be one per spell level with most of the math already done. (I prefer this when adding creatures to encounters, for example).

I have been pulling in some of your changes, but I have more coming. So .. this will be taken as (very welcome!) advice. ;)

**Comment by ebullient** [comment]
As for the bit about PHB being the default... there is no default. There is only what was used in examples.

**Comment by teunvdingenen** [comment]
Let me know if there is anything else I can do, I hope these commits are useful.

**Comment by ebullient** [comment]
They are!!

**Comment by ebullient** [comment]
included in #579

**Comment by ebullient** [comment]
@teunvdingenen -- if you have time to try the latest snapshot, that would be amazing!

**Pull request closed without merging**
