### PR TITLE
Removed duplicates in sourceMap.md

### PR DESCRIPTION
**Pull request by OneRadRedDad**
SCC entries had duplicates. Removed them.

### CODE REVIEW

**Comment by ebullient** [comment]
Ah. These aren't duplicates, exactly. I see what happened.

SourceMap.md is generated, so I'll need you (if you wouldn't mind) to make the change here instead: 

https://github.com/ebullient/ttrpg-convert-cli/blob/main/src/main/resources/sourceMap.json

Specifically, to address the duplicates, we need to choose one (either the `-` or the `_` .. which is used more often in the other json sources?), and make the other an alias:

```json
  "config5e": {
    "abvToName": {
    ...
      "SCC-ARiR": "A Reckoning in Ruins",
      "SCC-CK": "Campus Kerfuffle",
      "SCC-HfMT": "Hunt for Mage Tower",
      "SCC-TMM": "The Magister's Masquerade",
      "SCC_ARiR": "A Reckoning in Ruins",
      "SCC_CK": "Campus Kerfuffle",
      "SCC_HfMT": "Hunt for Mage Tower",
      "SCC_TMM": "The Magister's Masquerade",
       ...
    },
    "longToAbv": {
       ...
       "SCC-TMM": "SCC_TMM"
       ...
    }
}
```

That last is just an example of how to define the alias. So, choose one set to keep in "abvToName", and map the other set in "longToAbv".

Or.. just tell me I should do it. ;)

**Comment by OneRadRedDad** [comment]
I think I did that right? I'm new to the world of json, so let me know if something needs changed.

**Comment by OneRadRedDad** [comment]
I updated another readme, too. Oopsies! I thought there was a way to separate pull requests. Sorry about that; I'm still new to git.

**Comment by ebullient** [comment]
All is well, and thank you!

In the future, make a PR from a branch (rather than the main branch of your fork).

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-branches

**Pull request merged**
