### PR TITLE
Pf2e Changes

### LINKED ISSUE #173: PF2e Item Variants
How difficult would it be to show variants of items like how PF2eTools shows them?

Also, if I wanted to attempt adding it and submitting a PR, how do you debug this project in jetbrains idea?

image

image

Example JSON codeblocks

```json
{
			"name": "Goggles of Night",
			"source": "CRB",
			"page": 610,
			"type": "Item",
			"level": "5+",
			"traits": [
				"invested",
				"magical",
				"transmutation"
			],
			"usage": "worn eyepiece",
			"bulk": "\u2014",
			"category": "Worn",
			"entries": [
				"The opaque crystal lenses of these sleek goggles do not obscure vision, but rather enhance it. While wearing the goggles, you gain a +1 item bonus to {@skill Perception} checks involving sight.",
				{
					"type": "ability",
					"style": "compact",
					"activity": {
						"number": 1,
						"unit": "action"
					},
					"components": [
						"{@action Interact}"
					],
					"frequency": {
						"unit": "day",
						"number": 1
					},
					"entries": [
						"Rotating the lenses 90 degrees, you gain {@ability darkvision} for 1 hour."
					]
				}
			],
			"generic": "G",
			"variants": [
				{
					"level": 5,
					"price": {
						"coin": "gp",
						"amount": 150
					},
					"entries": [],
					"variantType": "goggles of night"
				},
				{
					"variantType": "greater goggles of night",
					"level": 11,
					"price": {
						"coin": "gp",
						"amount": 1250
					},
					"entries": [
						"The item bonus is +2, and the {@ability darkvision} lasts until you rotate the lenses back or the item is no longer invested by you, whichever comes first."
					]
				},
				{
					"variantType": "major goggles of night",
					"level": 18,
					"price": {
						"coin": "gp",
						"amount": 20000
					},
					"entries": [
						"The item bonus is +3, and the goggles grant {@ability darkvision||greater darkvision}, which lasts until you rotate the lenses back or the item is no longer invested by you, whichever comes first."
					]
				}
			]
},
{
			"name": "Healing Potion",
			"source": "CRB",
			"page": 563,
			"otherSources": {
				"Reprinted": [
					"BB|52"
				]
			},
			"type": "Item",
			"level": "1+",
			"traits": [
				"consumable",
				"healing",
				"magical",
				"necromancy",
				"potion"
			],
			"usage": "held in 1 hand",
			"bulk": "L",
			"activate": {
				"activity": {
					"number": 1,
					"unit": "action"
				},
				"components": [
					"{@action Interact}"
				]
			},
			"category": "Potion",
			"entries": [
				"A healing potion is a vial of a ruby-red liquid that imparts a tingling sensation as the drinker's wounds heal rapidly. When you drink a healing potion, you regain the listed number of Hit Points."
			],
			"generic": "G",
			"variants": [
				{
					"variantType": "minor",
					"level": 1,
					"equipment": true,
					"price": {
						"coin": "gp",
						"amount": 4
					},
					"entries": [
						"The potion restores {@dice 1d8} Hit Points."
					],
					"_mod": {
						"entries": {
							"with": "{@dice 1d8}"
						}
					}
				},
				{
					"variantType": "lesser",
					"level": 3,
					"price": {
						"coin": "gp",
						"amount": 12
					},
					"entries": [
						"The potion restores {@dice 2d8+5} Hit Points."
					],
					"_mod": {
						"entries": {
							"with": "{@dice 2d8+5}"
						}
					}
				},
				{
					"variantType": "moderate",
					"level": 6,
					"price": {
						"coin": "gp",
						"amount": 50
					},
					"entries": [
						"The potion restores {@dice 3d8+10} Hit Points."
					],
					"_mod": {
						"entries": {
							"with": "{@dice 3d8+10}"
						}
					}
				},
				{
					"variantType": "greater",
					"level": 12,
					"price": {
						"coin": "gp",
						"amount": 400
					},
					"entries": [
						"The potion restores {@dice 6d8+20} Hit Points."
					],
					"_mod": {
						"entries": {
							"with": "{@dice 6d8+20}"
						}
					}
				},
				{
					"variantType": "major",
					"level": 18,
					"price": {
						"coin": "gp",
						"amount": 5000
					},
					"entries": [
						"The potion restores {@dice 8d8+30} Hit Points."
					],
					"_mod": {
						"entries": {
							"with": "{@dice 8d8+30}"
						}
					}
				}
			],
			"_vmod": {
				"entriesMode": "generic",
				"entries": {
					"mode": "replaceTxt",
					"replace": "the listed number of"
				}
			}
},
```

### PR DESCRIPTION
**Pull request by Caedis**
Closes #173 

Item Variants  
Crafting Reqs for items  
Fixed ability adominations (added frequency and activity (duration))

Preview (ignore double colons, its from pf2-compendium.css):
image

image

image

### CODE REVIEW

**Comment by Caedis** [comment]
Just noticed another issue with the adomination callouts, its missing the type of activation besides actions, like Cast A Spell, Command, Interact, and Envision

**Comment by Caedis** [comment]
image

**Comment by Caedis** [comment]
May have to have variants be their own files so that links from https://github.com/Obsidian-TTRPG-Community/Pathfinder-2E-SRD-Markdown/blob/main/fantasy-bestiary/Template-2ETools-Monster-Handlebar.md work properly

**Comment by ebullient** [comment]
Yea. I was toying with that idea, too.  Separate variant documents with links to them (or even an embed) could suffice?

Note: on the 5e side, I detect variants while the index is being created (which means variants are later processed like any other thing in the index), so we may want to do that here. 

Also: squash your commits into one (when you're ready), and don't use merge commits (really messy history). Rebase for the win. Backup branches are your friend, so your changes aren't lost if you mess up. ;)

**Comment by Caedis** [comment]
yeah, accidentally had my repo set to merge and not rebase and didnt notice.

**Comment by Caedis** [comment]
Much better

**Review by ebullient — APPROVED** [review]
Brilliant. Thank you!

**Pull request merged**
